version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.6
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "6831:6831/udp"
      - "16686:16686"
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: sa
      RABBITMQ_DEFAULT_PASS:
    ports:
      - "15672:15672"
